version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: bitebase/frontend:latest
    container_name: bitebase-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://apis.bitebase.app
      - VITE_AGENTIC_URL=https://agentics.bitebase.app
    networks:
      - bitebase-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: bitebase/backend:latest
    container_name: bitebase-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://bitebase:${DB_PASSWORD}@db:5432/bitebase
      - OLLAMA_URL=http://ollama:11434
      - LANGFLOW_URL=http://langflow:7860
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
      langflow:
        condition: service_started
    networks:
      - bitebase-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database Service
  db:
    image: postgres:15-alpine
    container_name: bitebase-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bitebase
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bitebase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bitebase-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitebase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: bitebase-ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - bitebase-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Langflow Service
  langflow:
    image: langflowai/langflow:latest
    container_name: bitebase-langflow
    restart: unless-stopped
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
      - LANGFLOW_SERVER_HOST=0.0.0.0
      - LANGFLOW_SERVER_PORT=7860
    volumes:
      - langflow_data:/app/langflow
    networks:
      - bitebase-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bitebase-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
      langflow:
        condition: service_healthy
    networks:
      - bitebase-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bitebase-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    name: bitebase-postgres_data
  ollama_data:
    name: bitebase-ollama_data
  langflow_data:
    name: bitebase-langflow_data 