
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));
const AIPage = lazy(() => import("./pages/AIPage.tsx"));
const CompetitorAnalysis = lazy(() => import("./pages/CompetitorAnalysis.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/profile", element: <Profile />},
	{ path: "/settings", element: <UserGuard><Settings /></UserGuard>},
	{ path: "/ai", element: <UserGuard><AIPage /></UserGuard>},
	{ path: "/competitor-analysis", element: <UserGuard><CompetitorAnalysis /></UserGuard>},

];
